### ISSUE TITLE
Doesn't sync data for Main account (Home Admin)

### ISSUE THREAD

**Issue by OminusHush** [Gurky-Kronos/PlexWatchMigrator#1]
Your script works really well, thanks for sharing it. The only issue is that it doesn't seem to sync the watch list for the main account on a Plex Pass.

Stripping down the code and setting it to print the **user_list** from the defined **get_user_list** doesn't display my main account. It displays all other accounts, shared and other Home users, but not the main account linked to Plex. Do you know if there is any way to fix this?

**Comment by Gurky-Kronos** [comment]
Not my code sorry and this doesn't have support, it would be best to ask any plex share groups you are in.
